### ISSUE TITLE
TypeError: this.callback is not a function

### ISSUE THREAD

**Issue by rhclayto** [ClaudeBot/hubot-wikipedia#3]
Hi, really cool script!

However, in my case i have only been able to get it to work if I remove the options object from the respond functions. If I do that all works as expected, but if I don't, I get the following error:

```
[Mon Jul 04 2016 05:40:09 GMT-0600 (MDT)] ERROR TypeError: this.callback is not a function
  at TextListener.Listener.call (/var/www/hosting/example/com/hubot-webscale/node_modules/hubot/src/listener.coffee:27:8)
  at Robot.receive (/var/www/hosting/example/com/hubot-webscale/node_modules/hubot/src/robot.coffee:197:31)
  at Webscale.Adapter.receive (/var/www/hosting/example/com/hubot-webscale/node_modules/hubot/src/adapter.coffee:66:12)
  at Socket.<anonymous> (/var/www/hosting/example/com/hubot-webscale/src/hubot-webscale.coffee:68:10)
  at emitOne (events.js:90:13)
  at Socket.emit (events.js:182:7)
  at Socket.onevent (/var/www/hosting/example/com/hubot-webscale/node_modules/socket.io/lib/socket.js:330:8)
  at Socket.onpacket (/var/www/hosting/example/com/hubot-webscale/node_modules/socket.io/lib/socket.js:290:12)
  at Client.ondecoded (/var/www/hosting/example/com/hubot-webscale/node_modules/socket.io/lib/client.js:193:14)
  at Decoder.Emitter.emit (/var/www/hosting/example/com/hubot-webscale/node_modules/component-emitter/index.js:134:20)
  at Decoder.add (/var/www/hosting/example/com/hubot-webscale/node_modules/socket.io-parser/index.js:247:12)
  at Client.ondata (/var/www/hosting/example/com/hubot-webscale/node_modules/socket.io/lib/client.js:175:18)
  at emitOne (events.js:90:13)
  at Socket.emit (events.js:182:7)
  at Socket.onPacket (/var/www/hosting/example/com/hubot-webscale/node_modules/engine.io/lib/socket.js:99:14)
  at emitOne (events.js:95:20)
  at WebSocket.emit (events.js:182:7)
  at WebSocket.Transport.onPacket (/var/www/hosting/example/com/hubot-webscale/node_modules/engine.io/lib/transport.js:91:8)
  at WebSocket.Transport.onData (/var/www/hosting/example/com/hubot-webscale/node_modules/engine.io/lib/transport.js:102:8)
  at WebSocket.onData (/var/www/hosting/example/com/hubot-webscale/node_modules/engine.io/lib/transports/websocket.js:75:30)
  at emitTwo (events.js:100:13)
  at WebSocket.emit (events.js:185:7)
  at Receiver.ontext (/var/www/hosting/example/com/hubot-webscale/node_modules/ws/lib/WebSocket.js:816:10)
  at /var/www/hosting/example/com/hubot-webscale/node_modules/ws/lib/Receiver.js:477:18
  at Receiver.applyExtensions (/var/www/hosting/example/com/hubot-webscale/node_modules/ws/lib/Receiver.js:364:5)
  at /var/www/hosting/example/com/hubot-webscale/node_modules/ws/lib/Receiver.js:466:14
  at Receiver.flush (/var/www/hosting/example/com/hubot-webscale/node_modules/ws/lib/Receiver.js:340:3)
  at Receiver.opcodes.1.finish (/var/www/hosting/example/com/hubot-webscale/node_modules/ws/lib/Receiver.js:482:12)
  at Receiver.expectHandler (/var/www/hosting/example/com/hubot-webscale/node_modules/ws/lib/Receiver.js:451:33)
  at Receiver.add (/var/www/hosting/example/com/hubot-webscale/node_modules/ws/lib/Receiver.js:95:24)
  at Socket.realHandler (/var/www/hosting/example/com/hubot-webscale/node_modules/ws/lib/WebSocket.js:800:20)
  at emitOne (events.js:90:13)
  at Socket.emit (events.js:182:7)
  at readableAddChunk (_stream_readable.js:153:18)
  at Socket.Readable.push (_stream_readable.js:111:10)
  at TCP.onread (net.js:533:20)

```

Any ideas why this might be happening? 

Cheers,
H.

**Comment by MrSaints** [comment]
Hey @rhclayto,

Thanks for reporting this.

The reason for the error is because this script was designed for the latest version of Hubot where the signature for the `robot.respond` method is `(regex, options, callback)`, whereas, older versions of Hubot has a `robot.respond` signature of `(regex, callback)`.

It is likely that your version of Hubot does not support listener options, and it is expecting a callback function as the 2nd parameter, not an object / dictionary.

This changed was introduced in v0.0.3, see https://github.com/ClaudeBot/hubot-wikipedia/releases/tag/v0.0.3 for more information. As the release notes note, you might have to pin to `0.0.1` or remove the listener options for it to work (or upgrade Hubot). I'd recommend the latter so you can benefit from new updates / fixes. 

Thanks, and apologies for the inconvenience! 😄

**Comment by rhclayto** [comment]
That explains it. Many thanks for getting back to me on this. I'll close this.

**Comment by MrSaints** [comment]
No worries, let me know if you have any other questions 👍 @rhclayto
